In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("metaverse_transactions_dataset.csv")

In [3]:
df.head()

,timestamp,hour_of_day,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly
0,2022-04-11 12:47:27,12,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,796.949206,transfer,Europe,192.000,3,48,focused,established,18.75,low_risk
1,2022-06-14 19:12:46,19,0xd6e251c23cbf52dbd472f079147873e655d8096f,0x51e8fbe24f124e0e30a614e14401b9bbfed5384c,0.010000,purchase,South America,172.000,5,61,focused,established,25.00,low_risk
2,2022-01-18 16:26:59,16,0x2e0925b922fed01f6a85d213ae2718f54b8ca305,0x52c7911879f783d590af45bda0c0ef2b8536706f,778.197390,purchase,Asia,192.168,3,74,focused,established,31.25,low_risk
3,2022-06-15 09:20:04,9,0x93efefc25fcaf31d7695f28018d7a11ece55457f,0x8ac3b7bd531b3a833032f07d4e47c7af6ea7bace,300.838358,transfer,South America,172.000,8,111,high_value,veteran,36.75,low_risk
4,2022-02-18 14:35:30,14,0xad3b8de45d63f5cce28aef9a82cf30c397c6ceb9,0x6fdc047c2391615b3facd79b4588c7e9106e49f2,775.569344,sale,Africa,172.160,6,100,high_value,veteran,62.50,moderate_risk

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78600 entries, 0 to 78599
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   timestamp          78600 non-null  object
 1   hour_of_day        78600 non-null  int64
 2   sending_address    78600 non-null  object
 3   receiving_address  78600 non-null  object
 4   amount             78600 non-null  float64
 5   transaction_type   78600 non-null  object
 6   location_region    78600 non-null  object
 7   ip_prefix          78600 non-null  float64
 8   login_frequency    78600 non-null  int64
 9   session_duration   78600 non-null  int64
 10  purchase_pattern   78600 non-null  object
 11  age_group          78600 non-null  object
 12  risk_score         78600 non-null  float64
 13  anomaly            78600 non-null  object
dtypes: float64(3), int64(3), object(8)
memory usage: 8.4+ MB

In [5]:
df['timestamp']=pd.to_datetime(df['timestamp'])

In [6]:
df = df.drop_duplicates(subset =  None , keep  = 'first', inplace = False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78600 entries, 0 to 78599
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   timestamp          78600 non-null  datetime64[ns]
 1   hour_of_day        78600 non-null  int64
 2   sending_address    78600 non-null  object
 3   receiving_address  78600 non-null  object
 4   amount             78600 non-null  float64
 5   transaction_type   78600 non-null  object
 6   location_region    78600 non-null  object
 7   ip_prefix          78600 non-null  float64
 8   login_frequency    78600 non-null  int64
 9   session_duration   78600 non-null  int64
 10  purchase_pattern   78600 non-null  object
 11  age_group          78600 non-null  object
 12  risk_score         78600 non-null  float64
 13  anomaly            78600 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(3), object(7)
memory usage: 8.4+ MB

In [7]:
df=df.drop(['sending_address', 'receiving_address'],axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78600 entries, 0 to 78599
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         78600 non-null  datetime64[ns]
 1   hour_of_day       78600 non-null  int64
 2   amount            78600 non-null  float64
 3   transaction_type  78600 non-null  object
 4   location_region   78600 non-null  object
 5   ip_prefix         78600 non-null  float64
 6   login_frequency   78600 non-null  int64
 7   session_duration  78600 non-null  int64
 8   purchase_pattern  78600 non-null  object
 9   age_group         78600 non-null  object
 10  risk_score        78600 non-null  float64
 11  anomaly           78600 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(3), object(5)
memory usage: 7.2+ MB

In [8]:
df  =  df.dropna()

In [9]:
df.head()

,timestamp,hour_of_day,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly
0,2022-04-11 12:47:27,12,796.949206,transfer,Europe,192.000,3,48,focused,established,18.75,low_risk
1,2022-06-14 19:12:46,19,0.010000,purchase,South America,172.000,5,61,focused,established,25.00,low_risk
2,2022-01-18 16:26:59,16,778.197390,purchase,Asia,192.168,3,74,focused,established,31.25,low_risk
3,2022-06-15 09:20:04,9,300.838358,transfer,South America,172.000,8,111,high_value,veteran,36.75,low_risk
4,2022-02-18 14:35:30,14,775.569344,sale,Africa,172.160,6,100,high_value,veteran,62.50,moderate_risk

In [10]:
numerical_features = ["amount", "session_duration", "hour_of_day", "risk_score", "login_frequency"]
scaler = StandardScaler()
df[numerical_features] = scaler.fit_transform(df[numerical_features])

NameError: name 'StandardScaler' is not defined

In [11]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report



# Perform label encoding for categorical variables
label_encoder = LabelEncoder()
df['transaction_type'] = label_encoder.fit_transform(df['transaction_type'])
df['location_region'] = label_encoder.fit_transform(df['location_region'])
df['purchase_pattern'] = label_encoder.fit_transform(df['purchase_pattern'])
df['age_group'] = label_encoder.fit_transform(df['age_group'])
df['anomaly'] = label_encoder.fit_transform(df['anomaly'])

# Split the data into features and target variable
X = df.drop(columns=['anomaly', 'timestamp'])
y = df['anomaly']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
gb_classifier = GradientBoostingClassifier(n_estimators=100, random_state=42)
ada_classifier = AdaBoostClassifier(n_estimators=100, random_state=42)
nb_classifier = GaussianNB()
lr_classifier = LogisticRegression(max_iter=1000)
knn_classifier = KNeighborsClassifier()
svm_classifier = SVC(probability=True)

# Create a Voting Classifier with soft voting (predict class labels based on the average predicted probabilities)
voting_classifier = VotingClassifier(estimators=[
    ('rf', rf_classifier), 
    ('gb', gb_classifier), 
    ('ada', ada_classifier),
    ('nb', nb_classifier),
    ('lr', lr_classifier),
    ('knn', knn_classifier),
    ('svm', svm_classifier)
], voting='soft')

# Train the Voting Classifier
voting_classifier.fit(X_train, y_train)

# Make predictions
y_pred = voting_classifier.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))

C:\Users\prudh\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1251
           1       1.00      1.00      1.00     12848
           2       1.00      1.00      1.00      1621

    accuracy                           1.00     15720
   macro avg       1.00      1.00      1.00     15720
weighted avg       1.00      1.00      1.00     15720

In [ ]:
for clf in (rf_classifier,gb_classifier,ada_classifier,nb_classifier,lr_classifier,knn_classifier,svm_classifier):
    clf.fit(X_train, y_train)
    print(clf.__class__.__name__, clf.score(X_test, y_test))

RandomForestClassifier 1.0
GradientBoostingClassifier 1.0
AdaBoostClassifier 1.0
GaussianNB 0.8597328244274809

C:\Users\prudh\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression 0.9906488549618321
KNeighborsClassifier 0.994147582697201

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Assuming X_train, X_test, y_train, y_test are your training and testing data

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Simplify the model - Feature selection with RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_scaled, y_train)
feature_importances = clf.feature_importances_
model = SelectFromModel(clf, prefit=True)
X_train_selected = model.transform(X_train_scaled)
X_test_selected = model.transform(X_test_scaled)

# Regularization - Logistic Regression with L1 regularization
lr = LogisticRegression(penalty='l1', solver='liblinear', random_state=42)
lr.fit(X_train_selected, y_train)

# Cross-validation
cv_scores = cross_val_score(lr, X_train_selected, y_train, cv=5)
print("Cross-validation scores:", cv_scores)
print("Mean CV accuracy:", cv_scores.mean())

# Hyperparameter tuning with GridSearchCV
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}
grid_search = GridSearchCV(lr, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_selected, y_train)
print("Best hyperparameters:", grid_search.best_params_)
print("Best CV accuracy:", grid_search.best_score_)

# Evaluate on test set
y_pred = grid_search.predict(X_test_selected)
test_accuracy = accuracy_score(y_test, y_pred)
print("Test set accuracy:", test_accuracy)